language: ruby
sudo: required
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0
  - ruby-head
  - jruby-1.7
  - jruby-9.1.6.0
  - jruby-head
  - rbx-2.5
  - rbx-3.69
  - rbx-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update --system
  - gem install bundler
  - gem --version
  # Travis is on 64bit and there will be a cryptic aapt error w/o these libs.
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - sudo apt-get install binutils
